/* Generated By:JavaCC: Do not edit this line. ManchesterOWLParserConstants.java */
package org.protege.editor.owl.model.description.manchester;

public interface ManchesterOWLParserConstants {

    int EOF = 0;

    int OPENPAR = 5;

    int CLOSEPAR = 6;

    int OPENSQPAR = 7;

    int CLOSESQPAR = 8;

    int OPENBRACE = 9;

    int CLOSEBRACE = 10;

    int QUOTE = 11;

    int AND = 12;

    int OR = 13;

    int NOT = 14;

    int SOME = 15;

    int ALL = 16;

    int HAS = 17;

    int MIN = 18;

    int MAX = 19;

    int EXACT = 20;

    int THAT = 21;

    int COMMA = 22;

    int COMPOSITION = 23;

    int SUBCLASSOF = 24;

    int EQUIVALENTTO = 25;

    int DISJPOINTWITH = 26;

    int PLUS = 27;

    int UNION = 28;

    int MINUS = 29;

    int POSSIBLY = 30;

    int INV = 31;

    int MIN_EXC = 32;

    int MIN_INC = 33;

    int MAX_EXC = 34;

    int MAX_INC = 35;

    int PAT = 36;

    int LEN = 37;

    int INT = 38;

    int FLOAT = 39;

    int DOUBLE_CARET = 40;

    int BOOLEAN = 41;

    int STRING = 42;

    int IDENTIFIER = 43;

    int CLASSID = 44;

    int OBJECTPROPID = 45;

    int DATAPROPID = 46;

    int INDIVIDUALID = 47;

    int DATATYPEID = 48;

    int DATAVALUE = 49;

    int ERROR = 50;

    int DEFAULT = 0;

    String[] tokenImage = {"<EOF>", "\" \"", "\"\\n\"", "\"\\r\"", "\"\\r\\n\"", "\"(\"", "\")\"", "\"[\"", "\"]\"", "\"{\"", "\"}\"", "\"\\\"\"", "\"and\"", "\"or\"", "\"not\"", "\"some\"", "\"only\"", "\"value\"", "\"min\"", "\"max\"", "\"exactly\"", "\"that\"", "\",\"", "\"o\"", "\"subClassOf\"", "\"equivalentTo\"", "\"disjointWith\"", "\"plus\"", "\"union\"", "\"minus\"", "\"possibly\"", "\"inv\"", "\">\"", "\">=\"", "\"<\"", "\"<=\"", "\"pattern\"", "\"length\"", "<INT>", "<FLOAT>", "\"^^\"", "<BOOLEAN>", "<STRING>", "<IDENTIFIER>", "<CLASSID>", "<OBJECTPROPID>", "<DATAPROPID>", "<INDIVIDUALID>", "<DATATYPEID>", "<DATAVALUE>", "<ERROR>",};
}
