/* Generated By:JavaCC: Do not edit this line. ManchesterOWLParserTokenManager.java */
package org.protege.editor.owl.model.description.manchester;

import org.semanticweb.owl.model.*;

import java.net.URI;

public class ManchesterOWLParserTokenManager implements ManchesterOWLParserConstants {

    private EntityMapper entityMapper;

    private DataTypeMapper dataTypeMapper;

    private IdentifierKindExtractor extractor = new IdentifierKindExtractor();


    public void setEntityMapper(EntityMapper entityMapper) {
        this.entityMapper = entityMapper;
    }


    public void setDataTypeMapper(DataTypeMapper dataTypeMapper) {
        this.dataTypeMapper = dataTypeMapper;
    }


    private class IdentifierKindExtractor implements OWLEntityVisitor {

        private int kind;


        public int getKind() {
            return kind;
        }


        public void visit(OWLDataProperty owlDataProperty) {
            kind = ManchesterOWLParserConstants.DATAPROPID;
        }


        public void visit(OWLObjectProperty owlObjectProperty) {
            kind = ManchesterOWLParserConstants.OBJECTPROPID;
        }


        public void visit(OWLIndividual owlIndividual) {
            kind = ManchesterOWLParserConstants.INDIVIDUALID;
        }


        public void visit(OWLAnonymousIndividual individual) {
            kind = ManchesterOWLParserConstants.IDENTIFIER;
        }


        public void visit(OWLClass owlClass) {
            kind = ManchesterOWLParserConstants.CLASSID;
        }


        public void visit(OWLDataType dataType) {
            kind = ManchesterOWLParserConstants.DATATYPEID;
        }
    }


    public java.io.PrintStream debugStream = System.out;


    public void setDebugStream(java.io.PrintStream ds) {
        debugStream = ds;
    }


    private final int jjStopStringLiteralDfa_0(int pos, long active0) {
        switch (pos) {
            case 0:
                if ((active0 & 0x4000L) != 0L)
                    return 58;
                if ((active0 & 0x80000000000L) != 0L) {
                    jjmatchedKind = 46;
                    return 59;
                }
                if ((active0 & 0x187f8f68000L) != 0L) {
                    jjmatchedKind = 46;
                    return 60;
                }
                if ((active0 & 0x1000000L) != 0L) {
                    jjmatchedKind = 46;
                    return 14;
                }
                if ((active0 & 0x4090000L) != 0L)
                    return 60;
                if ((active0 & 0x7800000018L) != 0L)
                    return 59;
                return -1;
            case 1:
                if ((active0 & 0x10000L) != 0L)
                    return 60;
                if ((active0 & 0x85000000000L) != 0L)
                    return 59;
                if ((active0 & 0x187f9fe8000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 1;
                    return 60;
                }
                return -1;
            case 2:
                if ((active0 & 0x182f99c0000L) != 0L) {
                    if (jjmatchedPos != 2) {
                        jjmatchedKind = 46;
                        jjmatchedPos = 2;
                    }
                    return 60;
                }
                if ((active0 & 0x500628000L) != 0L)
                    return 60;
                return -1;
            case 3:
                if ((active0 & 0x183b8900000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 3;
                    return 60;
                }
                if ((active0 & 0x410c0000L) != 0L)
                    return 60;
                return -1;
            case 4:
                if ((active0 & 0x180100000L) != 0L)
                    return 60;
                if ((active0 & 0x18238800000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 4;
                    return 60;
                }
                return -1;
            case 5:
                if ((active0 & 0x8238800000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 5;
                    return 60;
                }
                if ((active0 & 0x10000000000L) != 0L)
                    return 60;
                return -1;
            case 6:
                if ((active0 & 0x8000800000L) != 0L)
                    return 60;
                if ((active0 & 0x238000000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 6;
                    return 60;
                }
                return -1;
            case 7:
                if ((active0 & 0x38000000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 7;
                    return 60;
                }
                if ((active0 & 0x200000000L) != 0L)
                    return 60;
                return -1;
            case 8:
                if ((active0 & 0x38000000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 8;
                    return 60;
                }
                return -1;
            case 9:
                if ((active0 & 0x8000000L) != 0L)
                    return 60;
                if ((active0 & 0x30000000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 9;
                    return 60;
                }
                return -1;
            case 10:
                if ((active0 & 0x30000000L) != 0L) {
                    jjmatchedKind = 46;
                    jjmatchedPos = 10;
                    return 60;
                }
                return -1;
            default:
                return -1;
        }
    }


    private final int jjStartNfa_0(int pos, long active0) {
        return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
    }


    private final int jjStopAtPos(int pos, int kind) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        return pos + 1;
    }


    private final int jjStartNfaWithStates_0(int pos, int kind, int state) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            return pos + 1;
        }
        return jjMoveNfa_0(state, pos + 1);
    }


    private final int jjMoveStringLiteralDfa0_0() {
        switch (curChar) {
            case 13:
                jjmatchedKind = 3;
                return jjMoveStringLiteralDfa1_0(0x10L);
            case 34:
                return jjStartNfaWithStates_0(0, 14, 58);
            case 40:
                return jjStopAtPos(0, 5);
            case 41:
                return jjStopAtPos(0, 6);
            case 44:
                return jjStopAtPos(0, 25);
            case 60:
                jjmatchedKind = 37;
                return jjMoveStringLiteralDfa1_0(0x4000000000L);
            case 62:
                jjmatchedKind = 35;
                return jjMoveStringLiteralDfa1_0(0x1000000000L);
            case 63:
                return jjStopAtPos(0, 9);
            case 91:
                return jjStopAtPos(0, 7);
            case 93:
                return jjStopAtPos(0, 8);
            case 94:
                return jjMoveStringLiteralDfa1_0(0x80000000000L);
            case 97:
                return jjMoveStringLiteralDfa1_0(0x8000L);
            case 100:
                return jjMoveStringLiteralDfa1_0(0x20000000L);
            case 101:
                return jjMoveStringLiteralDfa1_0(0x10800000L);
            case 105:
                return jjMoveStringLiteralDfa1_0(0x400000000L);
            case 108:
                return jjMoveStringLiteralDfa1_0(0x10000000000L);
            case 109:
                return jjMoveStringLiteralDfa1_0(0x100600000L);
            case 110:
                return jjMoveStringLiteralDfa1_0(0x20000L);
            case 111:
                jjmatchedKind = 26;
                return jjMoveStringLiteralDfa1_0(0x90000L);
            case 112:
                return jjMoveStringLiteralDfa1_0(0x8240000000L);
            case 115:
                return jjMoveStringLiteralDfa1_0(0x8040000L);
            case 116:
                return jjMoveStringLiteralDfa1_0(0x1000000L);
            case 117:
                return jjMoveStringLiteralDfa1_0(0x80000000L);
            case 118:
                return jjMoveStringLiteralDfa1_0(0x100000L);
            case 123:
                return jjStopAtPos(0, 12);
            case 125:
                return jjStopAtPos(0, 13);
            default:
                return jjMoveNfa_0(1, 0);
        }
    }


    private final int jjMoveStringLiteralDfa1_0(long active0) {
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(0, active0);
            return 1;
        }
        switch (curChar) {
            case 10:
                if ((active0 & 0x10L) != 0L)
                    return jjStopAtPos(1, 4);
                break;
            case 61:
                if ((active0 & 0x1000000000L) != 0L)
                    return jjStartNfaWithStates_0(1, 36, 59);
                else if ((active0 & 0x4000000000L) != 0L)
                    return jjStartNfaWithStates_0(1, 38, 59);
                break;
            case 94:
                if ((active0 & 0x80000000000L) != 0L)
                    return jjStartNfaWithStates_0(1, 43, 59);
                break;
            case 97:
                return jjMoveStringLiteralDfa2_0(active0, 0x8000500000L);
            case 101:
                return jjMoveStringLiteralDfa2_0(active0, 0x10000000000L);
            case 104:
                return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
            case 105:
                return jjMoveStringLiteralDfa2_0(active0, 0x120200000L);
            case 108:
                return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
            case 110:
                return jjMoveStringLiteralDfa2_0(active0, 0x480088000L);
            case 111:
                return jjMoveStringLiteralDfa2_0(active0, 0x200060000L);
            case 113:
                return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
            case 114:
                if ((active0 & 0x10000L) != 0L)
                    return jjStartNfaWithStates_0(1, 16, 60);
                break;
            case 117:
                return jjMoveStringLiteralDfa2_0(active0, 0x8000000L);
            case 120:
                return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
            default:
                break;
        }
        return jjStartNfa_0(0, active0);
    }


    private final int jjMoveStringLiteralDfa2_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(0, old0);
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(1, active0);
            return 2;
        }
        switch (curChar) {
            case 97:
                return jjMoveStringLiteralDfa3_0(active0, 0x1800000L);
            case 98:
                return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
            case 100:
                if ((active0 & 0x8000L) != 0L)
                    return jjStartNfaWithStates_0(2, 15, 60);
                break;
            case 105:
                return jjMoveStringLiteralDfa3_0(active0, 0x80000000L);
            case 108:
                return jjMoveStringLiteralDfa3_0(active0, 0x180000L);
            case 109:
                return jjMoveStringLiteralDfa3_0(active0, 0x40000L);
            case 110:
                if ((active0 & 0x200000L) != 0L) {
                    jjmatchedKind = 21;
                    jjmatchedPos = 2;
                }
                return jjMoveStringLiteralDfa3_0(active0, 0x10100000000L);
            case 115:
                return jjMoveStringLiteralDfa3_0(active0, 0x220000000L);
            case 116:
                if ((active0 & 0x20000L) != 0L)
                    return jjStartNfaWithStates_0(2, 17, 60);
                return jjMoveStringLiteralDfa3_0(active0, 0x8000000000L);
            case 117:
                return jjMoveStringLiteralDfa3_0(active0, 0x50000000L);
            case 118:
                if ((active0 & 0x400000000L) != 0L)
                    return jjStartNfaWithStates_0(2, 34, 60);
                break;
            case 120:
                if ((active0 & 0x400000L) != 0L)
                    return jjStartNfaWithStates_0(2, 22, 60);
                break;
            default:
                break;
        }
        return jjStartNfa_0(1, active0);
    }


    private final int jjMoveStringLiteralDfa3_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(1, old0);
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(2, active0);
            return 3;
        }
        switch (curChar) {
            case 67:
                return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
            case 99:
                return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
            case 101:
                if ((active0 & 0x40000L) != 0L)
                    return jjStartNfaWithStates_0(3, 18, 60);
                break;
            case 103:
                return jjMoveStringLiteralDfa4_0(active0, 0x10000000000L);
            case 105:
                return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
            case 106:
                return jjMoveStringLiteralDfa4_0(active0, 0x20000000L);
            case 111:
                return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
            case 115:
                if ((active0 & 0x40000000L) != 0L)
                    return jjStartNfaWithStates_0(3, 30, 60);
                return jjMoveStringLiteralDfa4_0(active0, 0x200000000L);
            case 116:
                if ((active0 & 0x1000000L) != 0L)
                    return jjStartNfaWithStates_0(3, 24, 60);
                return jjMoveStringLiteralDfa4_0(active0, 0x8000000000L);
            case 117:
                return jjMoveStringLiteralDfa4_0(active0, 0x100100000L);
            case 121:
                if ((active0 & 0x80000L) != 0L)
                    return jjStartNfaWithStates_0(3, 19, 60);
                break;
            default:
                break;
        }
        return jjStartNfa_0(2, active0);
    }


    private final int jjMoveStringLiteralDfa4_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(2, old0);
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(3, active0);
            return 4;
        }
        switch (curChar) {
            case 101:
                if ((active0 & 0x100000L) != 0L)
                    return jjStartNfaWithStates_0(4, 20, 60);
                return jjMoveStringLiteralDfa5_0(active0, 0x8000000000L);
            case 105:
                return jjMoveStringLiteralDfa5_0(active0, 0x200000000L);
            case 108:
                return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
            case 110:
                if ((active0 & 0x80000000L) != 0L)
                    return jjStartNfaWithStates_0(4, 31, 60);
                break;
            case 111:
                return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
            case 115:
                if ((active0 & 0x100000000L) != 0L)
                    return jjStartNfaWithStates_0(4, 32, 60);
                break;
            case 116:
                return jjMoveStringLiteralDfa5_0(active0, 0x10000800000L);
            case 118:
                return jjMoveStringLiteralDfa5_0(active0, 0x10000000L);
            default:
                break;
        }
        return jjStartNfa_0(3, active0);
    }


    private final int jjMoveStringLiteralDfa5_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(3, old0);
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(4, active0);
            return 5;
        }
        switch (curChar) {
            case 97:
                return jjMoveStringLiteralDfa6_0(active0, 0x18000000L);
            case 98:
                return jjMoveStringLiteralDfa6_0(active0, 0x200000000L);
            case 104:
                if ((active0 & 0x10000000000L) != 0L)
                    return jjStartNfaWithStates_0(5, 40, 60);
                break;
            case 105:
                return jjMoveStringLiteralDfa6_0(active0, 0x20000000L);
            case 108:
                return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
            case 114:
                return jjMoveStringLiteralDfa6_0(active0, 0x8000000000L);
            default:
                break;
        }
        return jjStartNfa_0(4, active0);
    }


    private final int jjMoveStringLiteralDfa6_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(4, old0);
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(5, active0);
            return 6;
        }
        switch (curChar) {
            case 108:
                return jjMoveStringLiteralDfa7_0(active0, 0x210000000L);
            case 110:
                if ((active0 & 0x8000000000L) != 0L)
                    return jjStartNfaWithStates_0(6, 39, 60);
                return jjMoveStringLiteralDfa7_0(active0, 0x20000000L);
            case 115:
                return jjMoveStringLiteralDfa7_0(active0, 0x8000000L);
            case 121:
                if ((active0 & 0x800000L) != 0L)
                    return jjStartNfaWithStates_0(6, 23, 60);
                break;
            default:
                break;
        }
        return jjStartNfa_0(5, active0);
    }


    private final int jjMoveStringLiteralDfa7_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(5, old0);
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(6, active0);
            return 7;
        }
        switch (curChar) {
            case 101:
                return jjMoveStringLiteralDfa8_0(active0, 0x10000000L);
            case 115:
                return jjMoveStringLiteralDfa8_0(active0, 0x8000000L);
            case 116:
                return jjMoveStringLiteralDfa8_0(active0, 0x20000000L);
            case 121:
                if ((active0 & 0x200000000L) != 0L)
                    return jjStartNfaWithStates_0(7, 33, 60);
                break;
            default:
                break;
        }
        return jjStartNfa_0(6, active0);
    }


    private final int jjMoveStringLiteralDfa8_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(6, old0);
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(7, active0);
            return 8;
        }
        switch (curChar) {
            case 79:
                return jjMoveStringLiteralDfa9_0(active0, 0x8000000L);
            case 87:
                return jjMoveStringLiteralDfa9_0(active0, 0x20000000L);
            case 110:
                return jjMoveStringLiteralDfa9_0(active0, 0x10000000L);
            default:
                break;
        }
        return jjStartNfa_0(7, active0);
    }


    private final int jjMoveStringLiteralDfa9_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(7, old0);
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(8, active0);
            return 9;
        }
        switch (curChar) {
            case 102:
                if ((active0 & 0x8000000L) != 0L)
                    return jjStartNfaWithStates_0(9, 27, 60);
                break;
            case 105:
                return jjMoveStringLiteralDfa10_0(active0, 0x20000000L);
            case 116:
                return jjMoveStringLiteralDfa10_0(active0, 0x10000000L);
            default:
                break;
        }
        return jjStartNfa_0(8, active0);
    }


    private final int jjMoveStringLiteralDfa10_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(8, old0);
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(9, active0);
            return 10;
        }
        switch (curChar) {
            case 84:
                return jjMoveStringLiteralDfa11_0(active0, 0x10000000L);
            case 116:
                return jjMoveStringLiteralDfa11_0(active0, 0x20000000L);
            default:
                break;
        }
        return jjStartNfa_0(9, active0);
    }


    private final int jjMoveStringLiteralDfa11_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(9, old0);
        try {
            curChar = input_stream.readChar();
        }
        catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(10, active0);
            return 11;
        }
        switch (curChar) {
            case 104:
                if ((active0 & 0x20000000L) != 0L)
                    return jjStartNfaWithStates_0(11, 29, 60);
                break;
            case 111:
                if ((active0 & 0x10000000L) != 0L)
                    return jjStartNfaWithStates_0(11, 28, 60);
                break;
            default:
                break;
        }
        return jjStartNfa_0(10, active0);
    }


    private final void jjCheckNAdd(int state) {
        if (jjrounds[state] != jjround) {
            jjstateSet[jjnewStateCnt++] = state;
            jjrounds[state] = jjround;
        }
    }


    private final void jjAddStates(int start, int end) {
        do {
            jjstateSet[jjnewStateCnt++] = jjnextStates[start];
        }
        while (start++ != end);
    }


    private final void jjCheckNAddTwoStates(int state1, int state2) {
        jjCheckNAdd(state1);
        jjCheckNAdd(state2);
    }


    private final void jjCheckNAddStates(int start, int end) {
        do {
            jjCheckNAdd(jjnextStates[start]);
        }
        while (start++ != end);
    }


    private final void jjCheckNAddStates(int start) {
        jjCheckNAdd(jjnextStates[start]);
        jjCheckNAdd(jjnextStates[start + 1]);
    }


    static final long[] jjbitVec0 = {0x0L, 0x0L, 0x40000L, 0x0L};

    static final long[] jjbitVec1 = {0x8000000000L, 0x0L, 0x0L, 0x0L};

    static final long[] jjbitVec2 = {0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL};

    static final long[] jjbitVec4 = {0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL};


    private final int jjMoveNfa_0(int startState, int curPos) {
        int[] nextStates;
        int startsAt = 0;
        jjnewStateCnt = 58;
        int i = 1;
        jjstateSet[0] = startState;
        int j, kind = 0x7fffffff;
        for (; ;) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64) {
                long l = 1L << curChar;
                MatchLoop:
                do {
                    switch (jjstateSet[--i]) {
                        case 1:
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAddStates(0, 5);
                            }
                            if ((0x3ff000000000000L & l) != 0L) {
                                if (kind > 41)
                                    kind = 41;
                                jjCheckNAddStates(6, 10);
                            }
                            else if (curChar == 39)
                                jjCheckNAddStates(11, 16);
                            else if (curChar == 34)
                                jjCheckNAddTwoStates(27, 29);
                            else if (curChar == 46)
                                jjCheckNAdd(7);
                            else if (curChar == 47)
                                jjstateSet[jjnewStateCnt++] = 3;
                            else if (curChar == 45)
                                jjstateSet[jjnewStateCnt++] = 0;
                            break;
                        case 14:
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(37);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(36);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(35);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(34);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(33);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(32);
                            }
                            break;
                        case 59:
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            break;
                        case 60:
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(37);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(36);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(35);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(34);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(33);
                            }
                            if ((0x7ff280000000000L & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(32);
                            }
                            break;
                        case 58:
                            if ((0xfffffffbffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(27, 28);
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if ((0x7fffecfefffff9ffL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(29, 30);
                            break;
                        case 0:
                            if (curChar == 62 && kind > 10)
                                kind = 10;
                            break;
                        case 4:
                            if (curChar == 47)
                                jjstateSet[jjnewStateCnt++] = 3;
                            break;
                        case 6:
                            if (curChar == 46)
                                jjCheckNAdd(7);
                            break;
                        case 7:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 42)
                                kind = 42;
                            jjCheckNAddStates(17, 19);
                            break;
                        case 9:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(10);
                            break;
                        case 10:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 42)
                                kind = 42;
                            jjCheckNAddTwoStates(10, 11);
                            break;
                        case 20:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 41)
                                kind = 41;
                            jjCheckNAddStates(6, 10);
                            break;
                        case 21:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 41)
                                kind = 41;
                            jjCheckNAdd(21);
                            break;
                        case 22:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(22, 23);
                            break;
                        case 23:
                            if (curChar != 46)
                                break;
                            if (kind > 42)
                                kind = 42;
                            jjCheckNAddStates(20, 22);
                            break;
                        case 24:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 42)
                                kind = 42;
                            jjCheckNAddStates(20, 22);
                            break;
                        case 25:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(25, 6);
                            break;
                        case 26:
                            if (curChar == 34)
                                jjCheckNAddTwoStates(27, 29);
                            break;
                        case 27:
                            if ((0xfffffffbffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(27, 28);
                            break;
                        case 28:
                            if (curChar == 34 && kind > 45)
                                kind = 45;
                            break;
                        case 29:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(29, 30);
                            break;
                        case 30:
                            if (curChar == 34 && kind > 52)
                                kind = 52;
                            break;
                        case 32:
                            if ((0x7ff280000000000L & l) == 0L)
                                break;
                            if (kind > 46)
                                kind = 46;
                            jjCheckNAdd(32);
                            break;
                        case 33:
                            if ((0x7ff280000000000L & l) == 0L)
                                break;
                            if (kind > 47)
                                kind = 47;
                            jjCheckNAdd(33);
                            break;
                        case 34:
                            if ((0x7ff280000000000L & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(34);
                            break;
                        case 35:
                            if ((0x7ff280000000000L & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(35);
                            break;
                        case 36:
                            if ((0x7ff280000000000L & l) == 0L)
                                break;
                            if (kind > 50)
                                kind = 50;
                            jjCheckNAdd(36);
                            break;
                        case 37:
                            if ((0x7ff280000000000L & l) == 0L)
                                break;
                            if (kind > 51)
                                kind = 51;
                            jjCheckNAdd(37);
                            break;
                        case 38:
                            if (curChar == 39)
                                jjCheckNAddStates(11, 16);
                            break;
                        case 39:
                            if ((0xffffff7fffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(39, 40);
                            break;
                        case 40:
                            if (curChar == 39 && kind > 46)
                                kind = 46;
                            break;
                        case 41:
                            if ((0xffffff7fffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(41, 42);
                            break;
                        case 42:
                            if (curChar == 39 && kind > 47)
                                kind = 47;
                            break;
                        case 43:
                            if ((0xffffff7fffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(43, 44);
                            break;
                        case 44:
                            if (curChar == 39 && kind > 48)
                                kind = 48;
                            break;
                        case 45:
                            if ((0xffffff7fffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(45, 46);
                            break;
                        case 46:
                            if (curChar == 39 && kind > 49)
                                kind = 49;
                            break;
                        case 47:
                            if ((0xffffff7fffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(47, 48);
                            break;
                        case 48:
                            if (curChar == 39 && kind > 50)
                                kind = 50;
                            break;
                        case 49:
                            if ((0xffffff7fffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(49, 50);
                            break;
                        case 50:
                            if (curChar == 39 && kind > 51)
                                kind = 51;
                            break;
                        case 51:
                            if ((0x7fffecfefffff9ffL & l) == 0L)
                                break;
                            if (kind > 46)
                                kind = 46;
                            jjCheckNAddStates(0, 5);
                            break;
                        case 52:
                            if ((0x7fffecfefffff9ffL & l) == 0L)
                                break;
                            if (kind > 46)
                                kind = 46;
                            jjCheckNAdd(52);
                            break;
                        case 53:
                            if ((0x7fffecfefffff9ffL & l) == 0L)
                                break;
                            if (kind > 47)
                                kind = 47;
                            jjCheckNAdd(53);
                            break;
                        case 54:
                            if ((0x7fffecfefffff9ffL & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(54);
                            break;
                        case 55:
                            if ((0x7fffecfefffff9ffL & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(55);
                            break;
                        case 56:
                            if ((0x7fffecfefffff9ffL & l) == 0L)
                                break;
                            if (kind > 50)
                                kind = 50;
                            jjCheckNAdd(56);
                            break;
                        case 57:
                            if ((0x7fffecfefffff9ffL & l) == 0L)
                                break;
                            if (kind > 51)
                                kind = 51;
                            jjCheckNAdd(57);
                            break;
                        default:
                            break;
                    }
                }
                while (i != startsAt);
            }
            else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                MatchLoop:
                do {
                    switch (jjstateSet[--i]) {
                        case 1:
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAddStates(0, 5);
                            }
                            if ((0x7fffffe07fffffeL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAddStates(23, 28);
                            }
                            if (curChar == 102)
                                jjstateSet[jjnewStateCnt++] = 18;
                            else if (curChar == 116)
                                jjstateSet[jjnewStateCnt++] = 14;
                            break;
                        case 14:
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(37);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(36);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(35);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(34);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(33);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(32);
                            }
                            if (curChar == 114)
                                jjstateSet[jjnewStateCnt++] = 13;
                            break;
                        case 59:
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            break;
                        case 60:
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(37);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(36);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(35);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(34);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(33);
                            }
                            if ((0x7fffffe87fffffeL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(32);
                            }
                            break;
                        case 58:
                            jjCheckNAddTwoStates(27, 28);
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if ((0xd7ffffffd7ffffffL & l) != 0L) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            break;
                        case 3:
                            if (curChar == 92 && kind > 11)
                                kind = 11;
                            break;
                        case 8:
                            if (curChar == 101)
                                jjAddStates(29, 30);
                            break;
                        case 11:
                            if ((0x104000000000L & l) != 0L && kind > 42)
                                kind = 42;
                            break;
                        case 12:
                            if (curChar == 101 && kind > 44)
                                kind = 44;
                            break;
                        case 13:
                            if (curChar == 117)
                                jjCheckNAdd(12);
                            break;
                        case 15:
                            if (curChar == 116)
                                jjstateSet[jjnewStateCnt++] = 14;
                            break;
                        case 16:
                            if (curChar == 115)
                                jjCheckNAdd(12);
                            break;
                        case 17:
                            if (curChar == 108)
                                jjstateSet[jjnewStateCnt++] = 16;
                            break;
                        case 18:
                            if (curChar == 97)
                                jjstateSet[jjnewStateCnt++] = 17;
                            break;
                        case 19:
                            if (curChar == 102)
                                jjstateSet[jjnewStateCnt++] = 18;
                            break;
                        case 27:
                            jjCheckNAddTwoStates(27, 28);
                            break;
                        case 31:
                            if ((0x7fffffe07fffffeL & l) == 0L)
                                break;
                            if (kind > 46)
                                kind = 46;
                            jjCheckNAddStates(23, 28);
                            break;
                        case 32:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 46)
                                kind = 46;
                            jjCheckNAdd(32);
                            break;
                        case 33:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 47)
                                kind = 47;
                            jjCheckNAdd(33);
                            break;
                        case 34:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(34);
                            break;
                        case 35:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(35);
                            break;
                        case 36:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 50)
                                kind = 50;
                            jjCheckNAdd(36);
                            break;
                        case 37:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 51)
                                kind = 51;
                            jjCheckNAdd(37);
                            break;
                        case 39:
                            jjAddStates(31, 32);
                            break;
                        case 41:
                            jjAddStates(33, 34);
                            break;
                        case 43:
                            jjAddStates(35, 36);
                            break;
                        case 45:
                            jjAddStates(37, 38);
                            break;
                        case 47:
                            jjAddStates(39, 40);
                            break;
                        case 49:
                            jjAddStates(41, 42);
                            break;
                        case 51:
                            if ((0xd7ffffffd7ffffffL & l) == 0L)
                                break;
                            if (kind > 46)
                                kind = 46;
                            jjCheckNAddStates(0, 5);
                            break;
                        case 52:
                            if ((0xd7ffffffd7ffffffL & l) == 0L)
                                break;
                            if (kind > 46)
                                kind = 46;
                            jjCheckNAdd(52);
                            break;
                        case 53:
                            if ((0xd7ffffffd7ffffffL & l) == 0L)
                                break;
                            if (kind > 47)
                                kind = 47;
                            jjCheckNAdd(53);
                            break;
                        case 54:
                            if ((0xd7ffffffd7ffffffL & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(54);
                            break;
                        case 55:
                            if ((0xd7ffffffd7ffffffL & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(55);
                            break;
                        case 56:
                            if ((0xd7ffffffd7ffffffL & l) == 0L)
                                break;
                            if (kind > 50)
                                kind = 50;
                            jjCheckNAdd(56);
                            break;
                        case 57:
                            if ((0xd7ffffffd7ffffffL & l) == 0L)
                                break;
                            if (kind > 51)
                                kind = 51;
                            jjCheckNAdd(57);
                            break;
                        default:
                            break;
                    }
                }
                while (i != startsAt);
            }
            else {
                int hiByte = (int) (curChar >> 8);
                int i1 = hiByte >> 6;
                long l1 = 1L << (hiByte & 077);
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                MatchLoop:
                do {
                    switch (jjstateSet[--i]) {
                        case 1:
                            if (jjCanMove_0(hiByte, i1, i2, l1, l2)) {
                                if (kind > 10)
                                    kind = 10;
                            }
                            if (jjCanMove_1(hiByte, i1, i2, l1, l2)) {
                                if (kind > 11)
                                    kind = 11;
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAddStates(0, 5);
                            }
                            break;
                        case 14:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            break;
                        case 59:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            break;
                        case 60:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            break;
                        case 58:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                                jjCheckNAddTwoStates(27, 28);
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 46)
                                    kind = 46;
                                jjCheckNAdd(52);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 47)
                                    kind = 47;
                                jjCheckNAdd(53);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(54);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 49)
                                    kind = 49;
                                jjCheckNAdd(55);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 50)
                                    kind = 50;
                                jjCheckNAdd(56);
                            }
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2)) {
                                if (kind > 51)
                                    kind = 51;
                                jjCheckNAdd(57);
                            }
                            break;
                        case 2:
                            if (jjCanMove_0(hiByte, i1, i2, l1, l2) && kind > 10)
                                kind = 10;
                            break;
                        case 5:
                            if (jjCanMove_1(hiByte, i1, i2, l1, l2) && kind > 11)
                                kind = 11;
                            break;
                        case 27:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                                jjCheckNAddTwoStates(27, 28);
                            break;
                        case 39:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                                jjAddStates(31, 32);
                            break;
                        case 41:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                                jjAddStates(33, 34);
                            break;
                        case 43:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                                jjAddStates(35, 36);
                            break;
                        case 45:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                                jjAddStates(37, 38);
                            break;
                        case 47:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                                jjAddStates(39, 40);
                            break;
                        case 49:
                            if (jjCanMove_2(hiByte, i1, i2, l1, l2))
                                jjAddStates(41, 42);
                            break;
                        case 51:
                            if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                                break;
                            if (kind > 46)
                                kind = 46;
                            jjCheckNAddStates(0, 5);
                            break;
                        case 52:
                            if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                                break;
                            if (kind > 46)
                                kind = 46;
                            jjCheckNAdd(52);
                            break;
                        case 53:
                            if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                                break;
                            if (kind > 47)
                                kind = 47;
                            jjCheckNAdd(53);
                            break;
                        case 54:
                            if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(54);
                            break;
                        case 55:
                            if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(55);
                            break;
                        case 56:
                            if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                                break;
                            if (kind > 50)
                                kind = 50;
                            jjCheckNAdd(56);
                            break;
                        case 57:
                            if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                                break;
                            if (kind > 51)
                                kind = 51;
                            jjCheckNAdd(57);
                            break;
                        default:
                            break;
                    }
                }
                while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 58 - (jjnewStateCnt = startsAt)))
                return curPos;
            try {
                curChar = input_stream.readChar();
            }
            catch (java.io.IOException e) {
                return curPos;
            }
        }
    }


    static final int[] jjnextStates = {52, 53, 54, 55, 56, 57, 21, 22, 23, 25, 6, 39, 41, 43, 45, 47, 49, 7, 8, 11, 24, 8, 11, 32, 33, 34, 35, 36, 37, 9, 10, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,};


    private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2) {
        switch (hiByte) {
            case 33:
                return ((jjbitVec0[i2] & l2) != 0L);
            default:
                return false;
        }
    }


    private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2) {
        switch (hiByte) {
            case 34:
                return ((jjbitVec1[i2] & l2) != 0L);
            default:
                return false;
        }
    }


    private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2) {
        switch (hiByte) {
            case 0:
                return ((jjbitVec4[i2] & l2) != 0L);
            default:
                if ((jjbitVec2[i1] & l1) != 0L)
                    return true;
                return false;
        }
    }


    public static final String[] jjstrLiteralImages = {"", null, null, null, null, "\50", "\51", "\133", "\135", "\77", null, null, "\173", "\175", "\42", "\141\156\144", "\157\162", "\156\157\164", "\163\157\155\145", "\157\156\154\171", "\166\141\154\165\145", "\155\151\156", "\155\141\170", "\145\170\141\143\164\154\171", "\164\150\141\164", "\54", "\157", "\163\165\142\103\154\141\163\163\117\146", "\145\161\165\151\166\141\154\145\156\164\124\157", "\144\151\163\152\157\151\156\164\127\151\164\150", "\160\154\165\163", "\165\156\151\157\156", "\155\151\156\165\163", "\160\157\163\163\151\142\154\171", "\151\156\166", "\76", "\76\75", "\74", "\74\75", "\160\141\164\164\145\162\156", "\154\145\156\147\164\150", null, null, "\136\136", null, null, null, null, null, null, null, null, null, null,};

    public static final String[] lexStateNames = {"DEFAULT",};

    static final long[] jjtoToken = {0x3fffffffffffe1L,};

    static final long[] jjtoSkip = {0x1eL,};

    protected SimpleCharStream input_stream;

    private final int[] jjrounds = new int[58];

    private final int[] jjstateSet = new int[116];

    StringBuffer image;

    int jjimageLen;

    int lengthOfMatch;

    protected char curChar;


    public ManchesterOWLParserTokenManager(SimpleCharStream stream) {
        if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
        input_stream = stream;
    }


    public ManchesterOWLParserTokenManager(SimpleCharStream stream, int lexState) {
        this(stream);
        SwitchTo(lexState);
    }


    public void ReInit(SimpleCharStream stream) {
        jjmatchedPos = jjnewStateCnt = 0;
        curLexState = defaultLexState;
        input_stream = stream;
        ReInitRounds();
    }


    private final void ReInitRounds() {
        int i;
        jjround = 0x80000001;
        for (i = 58; i-- > 0;)
            jjrounds[i] = 0x80000000;
    }


    public void ReInit(SimpleCharStream stream, int lexState) {
        ReInit(stream);
        SwitchTo(lexState);
    }


    public void SwitchTo(int lexState) {
        if (lexState >= 1 || lexState < 0)
            throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.",
                                    TokenMgrError.INVALID_LEXICAL_STATE);
        else
            curLexState = lexState;
    }


    protected Token jjFillToken() {
        Token t = Token.newToken(jjmatchedKind);
        t.kind = jjmatchedKind;
        String im = jjstrLiteralImages[jjmatchedKind];
        t.image = (im == null) ? input_stream.GetImage() : im;
        t.beginLine = input_stream.getBeginLine();
        t.beginColumn = input_stream.getBeginColumn();
        t.endLine = input_stream.getEndLine();
        t.endColumn = input_stream.getEndColumn();
        return t;
    }


    int curLexState = 0;

    int defaultLexState = 0;

    int jjnewStateCnt;

    int jjround;

    int jjmatchedPos;

    int jjmatchedKind;


    public Token getNextToken() {
        int kind;
        Token specialToken = null;
        Token matchedToken;
        int curPos = 0;

        EOFLoop:
        for (; ;) {
            try {
                curChar = input_stream.BeginToken();
            }
            catch (java.io.IOException e) {
                jjmatchedKind = 0;
                matchedToken = jjFillToken();
                return matchedToken;
            }
            image = null;
            jjimageLen = 0;

            try {
                input_stream.backup(0);
                while (curChar <= 32 && (0x100000400L & (1L << curChar)) != 0L)
                    curChar = input_stream.BeginToken();
            }
            catch (java.io.IOException e1) {
                continue EOFLoop;
            }
            jjmatchedKind = 0x7fffffff;
            jjmatchedPos = 0;
            curPos = jjMoveStringLiteralDfa0_0();
            if (jjmatchedPos == 0 && jjmatchedKind > 53) {
                jjmatchedKind = 53;
            }
            if (jjmatchedKind != 0x7fffffff) {
                if (jjmatchedPos + 1 < curPos)
                    input_stream.backup(curPos - jjmatchedPos - 1);
                if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
                    matchedToken = jjFillToken();
                    TokenLexicalActions(matchedToken);
                    return matchedToken;
                }
                else {
                    continue EOFLoop;
                }
            }
            int error_line = input_stream.getEndLine();
            int error_column = input_stream.getEndColumn();
            String error_after = null;
            boolean EOFSeen = false;
            try {
                input_stream.readChar();
                input_stream.backup(1);
            }
            catch (java.io.IOException e1) {
                EOFSeen = true;
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
                if (curChar == '\n' || curChar == '\r') {
                    error_line++;
                    error_column = 0;
                }
                else
                    error_column++;
            }
            if (!EOFSeen) {
                input_stream.backup(1);
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
            }
            throw new TokenMgrError(EOFSeen,
                                    curLexState,
                                    error_line,
                                    error_column,
                                    error_after,
                                    curChar,
                                    TokenMgrError.LEXICAL_ERROR);
        }
    }


    void TokenLexicalActions(Token matchedToken) {
        switch (jjmatchedKind) {
            case 46:
                if (image == null)
                    image = new StringBuffer();
                image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                OWLEntity owlEntity = entityMapper.getOWLEntity(image.toString());
                if (owlEntity == null) {
                    // Could be a data type
                    URI dataTypeURI = dataTypeMapper.getOWLDataTypeURI(image.toString());
                    if (dataTypeURI != null) {
                        matchedToken.kind = ManchesterOWLParserConstants.DATATYPEID;
                    }
                }
                else {
                    owlEntity.accept(extractor);
                    matchedToken.kind = extractor.getKind();
                }
                break;
            default:
                break;
        }
    }
}
