package org.protege.editor.owl.model.entity;

import org.apache.log4j.Logger;
import org.protege.editor.owl.model.OWLModelManager;
import org.semanticweb.owl.model.*;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
/*
* Copyright (C) 2007, University of Manchester
*
* Modifications to the initial code base are copyright of their
* respective authors, or their employers as appropriate.  Authorship
* of the modifications may be determined from the ChangeLog placed at
* the end of this file.
*
* This library is free software; you can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public
* License as published by the Free Software Foundation; either
* version 2.1 of the License, or (at your option) any later version.

* This library is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
* Lesser General Public License for more details.

* You should have received a copy of the GNU Lesser General Public
* License along with this library; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

/**
 * Author: drummond<br>
 * http://www.cs.man.ac.uk/~drummond/<br><br>
 * <p/>
 * The University Of Manchester<br>
 * Bio Health Informatics Group<br>
 * Date: Jul 28, 2008<br><br>
 */
public class CustomOWLEntityFactory implements OWLEntityFactory {

    private Logger logger = Logger.getLogger(CustomOWLEntityFactory.class);

    private OWLModelManager mngr;

    private static AutoIDGenerator autoIDGenerator; // only a single generator between instances

    private LabelDescriptor labelDescriptor;


    public CustomOWLEntityFactory(OWLModelManager mngr) {
        this.mngr = mngr;
    }


    public OWLEntityCreationSet<OWLClass> createOWLClass(String shortName, URI baseURI) throws OWLEntityCreationException {
        return createOWLEntity(OWLClass.class, shortName, baseURI);
    }


    public OWLEntityCreationSet<OWLObjectProperty> createOWLObjectProperty(String shortName, URI baseURI) throws OWLEntityCreationException {
        return createOWLEntity(OWLObjectProperty.class, shortName, baseURI);
    }


    public OWLEntityCreationSet<OWLDataProperty> createOWLDataProperty(String shortName, URI baseURI) throws OWLEntityCreationException {
        return createOWLEntity(OWLDataProperty.class, shortName, baseURI);
    }


    public OWLEntityCreationSet<OWLNamedIndividual> createOWLIndividual(String shortName, URI baseURI) throws OWLEntityCreationException {
        return createOWLEntity(OWLNamedIndividual.class, shortName, baseURI);
    }


    public <T extends OWLEntity> OWLEntityCreationSet<T> createOWLEntity(Class<T> type, String shortName, URI baseURI) throws OWLEntityCreationException {
        try {

            if (baseURI == null){
                if (useDefaultBaseURI()){
                    baseURI = getDefaultBaseURI();
                }
                if (baseURI == null){
                    baseURI = mngr.getActiveOntology().getURI();
                }
            }

            URI uri;
            String id = null;
            if (isFragmentAutoGenerated()){
                do{
                    id = getAutoIDGenerator().getNextID(type);
                    uri = createURI(id, baseURI);
                } while (isURIAlreadyUsed(uri)); // don't pun unnecessarily
            }
            else {
                uri = createURI(shortName, baseURI);

                if (isURIAlreadyUsed(type, uri)){
                    throw new OWLEntityCreationException("Entity already exists: " + uri);
                }

                if (isGenerateIDLabel()){
                    id = getAutoIDGenerator().getNextID(type); // critical it is unique?
                }
            }

            T entity = getOWLEntity(type, uri);

            List<OWLOntologyChange> changes = new ArrayList<OWLOntologyChange>();

            if (isGenerateIDLabel()){
                changes.addAll(createLabel(entity, id));
            }

            if (isGenerateNameLabel()){
                changes.addAll(createLabel(entity, shortName));
            }

            OWLDataFactory df = mngr.getOWLDataFactory();
            OWLAxiom ax = df.getOWLDeclarationAxiom(entity);
            changes.add(new AddAxiom(mngr.getActiveOntology(), ax));

            return new OWLEntityCreationSet<T>(entity, changes);
        }
        catch (URISyntaxException e) {
            throw new OWLEntityCreationException(e);
        }
        catch (AutoIDException e) {
            throw new OWLEntityCreationException(e);
        }
    }


    public <T extends OWLEntity> OWLEntityCreationSet<T> preview(Class<T> type, String shortName, URI baseURI) throws OWLEntityCreationException {
        // There is probably a better way round this.
        if (getAutoIDGenerator() instanceof Revertable){
            ((Revertable)getAutoIDGenerator()).checkpoint();
        }
        try{
            return createOWLEntity(type, shortName, baseURI);
        }
        catch(OWLEntityCreationException e){
            throw e;
        }
        finally{
            if (getAutoIDGenerator() instanceof Revertable){
                ((Revertable)getAutoIDGenerator()).revert();
            }
        }
    }


    protected URI createURI(String fragment, URI baseURI) throws URISyntaxException {
        fragment = fragment.replace(" ", "_");
        if (baseURI == null){
            if (useDefaultBaseURI()){
                baseURI = EntityCreationPreferences.getDefaultBaseURI();
            }
            else{
                baseURI = mngr.getActiveOntology().getURI();
            }
        }
        String base = baseURI.toString().replace(" ", "_");
        if (!base.endsWith("#") && !base.endsWith("/")) {
            base += EntityCreationPreferences.getDefaultSeparator();
        }
        return new URI(base + fragment);
    }


    private List<? extends OWLOntologyChange> createLabel(OWLEntity owlEntity, String value) {
        LabelDescriptor descr = getLabelDescriptor();
        URI uri = descr.getURI();
        String lang = descr.getLanguage();

        OWLDataFactory df = mngr.getOWLDataFactory();
        OWLLiteral con = df.getRDFTextLiteral(value, lang);
        OWLAnnotationProperty prop = df.getOWLAnnotationProperty(uri);
        OWLAxiom ax = df.getOWLAnnotationAssertionAxiom(owlEntity, prop, con);
        return Collections.singletonList(new AddAxiom(mngr.getActiveOntology(), ax));
    }


    private LabelDescriptor getLabelDescriptor() {
        Class<? extends LabelDescriptor> cls = EntityCreationPreferences.getLabelDescriptorClass();
        if (labelDescriptor == null || !cls.equals(labelDescriptor.getClass())){
            try {
                labelDescriptor = cls.newInstance();
            }
            catch (InstantiationException e) {
                logger.error("Cannot create label descriptor", e);
            }
            catch (IllegalAccessException e) {
                logger.error("Cannot create label descriptor", e);
            }
        }
        return labelDescriptor;
    }


    private AutoIDGenerator getAutoIDGenerator() {
        final Class<? extends AutoIDGenerator> prefAutoIDClass = EntityCreationPreferences.getAutoIDGeneratorClass();
        if (autoIDGenerator == null || !prefAutoIDClass.equals(autoIDGenerator.getClass())){
            try {
                autoIDGenerator = prefAutoIDClass.newInstance();
            }
            catch (InstantiationException e) {
                logger.error("Cannot create auto ID generator", e);
            }
            catch (IllegalAccessException e) {
                logger.error("Cannot create auto ID generator", e);
            }
        }
        return autoIDGenerator;
    }


    private <T extends OWLEntity> boolean isURIAlreadyUsed(Class<T> type, URI uri) {
        for (OWLOntology ont : mngr.getOntologies()){
            if ((OWLClass.class.isAssignableFrom(type) && ont.containsClassReference(uri)) ||
                (OWLObjectProperty.class.isAssignableFrom(type) && ont.containsObjectPropertyReference(uri)) ||
                (OWLDataProperty.class.isAssignableFrom(type) && ont.containsDataPropertyReference(uri)) ||
                (OWLIndividual.class.isAssignableFrom(type) && ont.containsIndividualReference(uri))){
                return true;
            }
        }
        return false;
    }


    private boolean isURIAlreadyUsed(URI uri) {
        for (OWLOntology ont : mngr.getOntologies()){
            if (ont.containsClassReference(uri) ||
                ont.containsObjectPropertyReference(uri) ||
                ont.containsDataPropertyReference(uri) ||
                ont.containsIndividualReference(uri)){
                return true;
            }
        }
        return false;
    }


    private <T extends OWLEntity> T getOWLEntity(Class<T> type, URI uri) {
        if (OWLClass.class.isAssignableFrom(type)){
            return (T)mngr.getOWLDataFactory().getOWLClass(uri);
        }
        else if (OWLObjectProperty.class.isAssignableFrom(type)){
            return (T)mngr.getOWLDataFactory().getOWLObjectProperty(uri);
        }
        else if (OWLDataProperty.class.isAssignableFrom(type)){
            return (T)mngr.getOWLDataFactory().getOWLDataProperty(uri);
        }
        else if (OWLNamedIndividual.class.isAssignableFrom(type)){
            return (T)mngr.getOWLDataFactory().getOWLNamedIndividual(uri);
        }
        return null;
    }


    protected boolean useDefaultBaseURI() {
        return EntityCreationPreferences.useDefaultBaseURI();
    }


    protected boolean isFragmentAutoGenerated() {
        return EntityCreationPreferences.isFragmentAutoGenerated();
    }


    protected boolean isGenerateNameLabel() {
        return EntityCreationPreferences.isGenerateNameLabel();
    }


    protected boolean isGenerateIDLabel() {
        return EntityCreationPreferences.isGenerateIDLabel();
    }


    protected URI getDefaultBaseURI() {
        return EntityCreationPreferences.getDefaultBaseURI();
    }


}
